# Generated by Django 3.1 on 2020-08-25 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=50)),
                ('team2', models.CharField(max_length=50)),
                ('winner', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('league_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contest.league')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('R', 'Regular'), ('QF', 'Quarter Final'), ('SF', 'Semi Final'), ('P', 'PlayOff')], max_length=50)),
                ('result', models.CharField(choices=[('W', 'Win'), ('L', 'Lose'), ('D', 'Draw')], max_length=20)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contest.match')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Groups.usergroup')),
            ],
        ),
        migrations.CreateModel(
            name='GroupLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Groups.group')),
                ('league_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contest.league')),
            ],
        ),
    ]
