# Generated by Django 3.1 on 2020-08-27 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0002_auto_20200826_0727'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Contest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Groups.group')),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contest.match')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'group_id', 'match_id')},
            },
        ),
        migrations.RemoveField(
            model_name='usermatch',
            name='match_id',
        ),
        migrations.RemoveField(
            model_name='usermatch',
            name='user_id',
        ),
        migrations.AddField(
            model_name='league',
            name='groups',
            field=models.ManyToManyField(to='Groups.Group'),
        ),
        migrations.DeleteModel(
            name='GroupLeague',
        ),
        migrations.DeleteModel(
            name='UserMatch',
        ),
    ]
