# Generated by Django 2.2 on 2020-11-13 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Groups', '0001_initial'),
        ('Contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Groups.Group'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='Contest.Match'),
        ),
    ]
