# Generated by Django 3.1 on 2020-08-31 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0002_auto_20200827_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prediction',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='prediction',
            old_name='match_id',
            new_name='match',
        ),
        migrations.RenameField(
            model_name='prediction',
            old_name='user_id',
            new_name='user',
        ),
    ]
