# Generated by Django 3.1 on 2020-09-09 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0004_auto_20200904_0523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='league_id',
            new_name='league',
        ),
    ]
