# Generated by Django 3.1 on 2020-09-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0007_auto_20200909_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
