# Generated by Django 3.1 on 2020-09-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0011_auto_20200910_1315'),
        ('Contest', '0008_auto_20200909_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='groups',
            field=models.ManyToManyField(blank=True, to='Groups.Group'),
        ),
    ]
