# Generated by Django 3.1 on 2020-11-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0010_auto_20200910_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='api_id',
            field=models.IntegerField(default=0),
        ),
    ]
