# Generated by Django 3.1 on 2020-10-29 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0010_auto_20200910_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='Contest.match'),
        ),
    ]
