# Generated by Django 2.2 on 2020-11-12 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0012_auto_20201104_1235'),
        ('Contest', '0011_auto_20201029_1155'),
    ]

    operations = [
    ]
