# Generated by Django 2.2 on 2020-11-12 07:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Groups', '0011_auto_20200910_1315'),
        ('Contest', '0013_merge_20201112_0641'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prediction',
            unique_together={('user', 'group', 'match')},
        ),
    ]
