# Generated by Django 2.2 on 2020-11-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('privacy', models.CharField(choices=[('public', 'public'), ('private', 'private')], default='PR', max_length=10)),
            ],
        ),
    ]
