# Generated by Django 3.1 on 2020-08-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0003_auto_20200827_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='privacy',
            field=models.CharField(choices=[('PB', 'public'), ('PR', 'private')], default='PR', max_length=10),
        ),
    ]
