# Generated by Django 3.1 on 2020-08-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0004_auto_20200828_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='privacy',
            field=models.CharField(blank=True, choices=[('PB', 'public'), ('PR', 'private')], default='PR', max_length=10, null=True),
        ),
    ]
