# Generated by Django 3.1 on 2020-08-31 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Groups', '0008_auto_20200831_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='admin_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_admin', to='auth.user'),
            preserve_default=False,
        ),
    ]
