# Generated by Django 3.1 on 2020-08-26 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0002_auto_20200826_0727'),
        ('User_profile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
