# Generated by Django 2.2 on 2020-11-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_profile', '0005_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
